import type { NextPage } from "next";
import Head from "next/head";
import { IGif } from "@giphy/js-types";
import { GIFContainer } from "../components/container";
import { getGiphyData } from "../lib/giphy";
import styles from "../styles/Home.module.css";
import { getTrending } from "../lib/trending";

interface Data {
  gif: IGif;
}

const Home: NextPage<Data> = ({ gif }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div style={{ margin: "0 auto", width: "80%" }}>
        <h1 className="title">GIF of the day</h1>
        <GIFContainer gif={gif} />
      </div>
    </div>
  );
};

export async function getServerSideProps() {
  const trending = await getTrending();
  const gif = await getGiphyData(trending);

  return {
    props: { gif }
  };
}

export default Home;
