import type { NextPage } from "next";
import Head from "next/head";
import { IGif } from "@giphy/js-types";
import { GIFContainer } from "../components/gifContainer";
import { getGiphyData } from "../lib/giphy";
import styles from "../styles/Home.module.css";
import { getTrending } from "../lib/trending";
import GameContainer from "../components/gameContainer";
import { useState } from "react";

interface Data {
  gifs: IGif[];
  trending: string;
}

const Home: NextPage<Data> = ({ gifs, trending }) => {
  const [gifIndex, setGifIndex] = useState(0);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div style={{ margin: "0 auto", width: "99%" }}>
        <h1 className="title">GIF of the day</h1>
        <GIFContainer gif={gifs[gifIndex]} />
        <GameContainer
          wordToGuess={trending.toLowerCase()}
          onGuess={() => setGifIndex(gifIndex + 1)}
        />
      </div>
    </div>
  );
};

export async function getServerSideProps() {
  const trending = await getTrending();
  const gifs = await getGiphyData(trending);

  return {
    props: { gifs, trending }
  };
}

export default Home;
